[Desktop Entry]
Type=X-GNOME-Metatheme
Name=02-Crunchy-orange
Comment=Variant of Ambiance theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=02-Crunchy-orange
MetacityTheme=02-Crunchy-orange
GtkColorScheme=base_color:#FAFAFA,fg_color:#4c4c4c,tooltip_fg_color:white,selected_bg_color:#f07746,selected_fg_color:white,text_color:#3C3C3C,bg_color:#F2F1F2,tooltip_bg_color:#373b3c,link_color:#f07746,light_grey:#cdcdcd
IconTheme=Mint-X-Dark
CursorTheme=default
ButtonLayout=close,minimize,maximize:menu
