[Desktop Entry]
Type=X-GNOME-Metatheme
Name=04-Crunchy-grey
Comment=Variant of Ambiance theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=04-Crunchy-grey
MetacityTheme=04-Crunchy-grey
GtkColorScheme=base_color:#FAFAFA,fg_color:#4c4c4c,tooltip_fg_color:white,selected_bg_color:#9E9EB3,selected_fg_color:white,text_color:#3C3C3C,bg_color:#F2F1F2,tooltip_bg_color:#373b3c,link_color:#9E9EB3,light_grey:#cdcdcd
IconTheme=Mint-X-Dark
CursorTheme=default
ButtonLayout=close,minimize,maximize:menu
